# Formatting constants
TAB = '\t'
SPACE_HYPHEN = ' - '
SPACE = ' '
INDENT1 = TAB + SPACE_HYPHEN
INDENT2 = 2*TAB + SPACE_HYPHEN
INDENT3 = 3*TAB + SPACE_HYPHEN
INDENT4 = 4*TAB + SPACE_HYPHEN
DATA_INDENT1 = TAB + SPACE
DATA_INDENT2 = 2*TAB + SPACE
DATA_INDENT3 = 3*TAB + SPACE
DATA_INDENT4 = 4*TAB + SPACE